### ISSUE TITLE
Decide 4th episode

### ISSUE THREAD

**Issue by hotchemi** [dexfm/dex.fm#3]
- [x] Schedule
- [x] Guest?
- [x] Recording venue
- [x] Agenda

**Comment by hotchemi** [comment]
### 4: Shownote

### 5: Shownote

**Comment by hkurokawa** [comment]
Here is what I'd like to ask Araki-san. Tell me which is interesting if any.

- How you'd become a Googler and started working on support library? Tell us your story.
- How do you usually work with other members? For example, I'm afraid working with Chris might be hard due to the time difference.
- It seems to me Android is developed by many small teams, each of which is of only a few members. How come? Do you think it's efficient?
- Sometimes I feel like a library published by a Googler is not inconsistent with the Android platform, like Agera. How do you think we, Android app. developers, should see that?
- What is your expectation to the Android app. developers?
- How do you think about Android tech communities? And especially about Japanese ones?

**Comment by hotchemi** [comment]
もう日本語で…

- Support libraryの意思決定はどの様にしているのか？(どのコンポーネントを実装するか、優先順位等)
- デザイナーとの協業はどの様にしている？
- 下位互換性は実際どの様に担保しているのか
----
- 荒木さんのこれまでの経歴等

**Comment by hotchemi** [comment]
あと、YahooのAndroidの書籍の宣伝？を5分程はさみます。

**Comment by hotchemi** [comment]
重要な告知的なことは support-v4 の小分けの話と最小 SDK バージョン上げる話ですかね。あと思いつくのは CoordinatorLayout と FlexboxLayout と ConstraintLayout の話などどうでしょうか。

**Comment by hotchemi** [comment]
Shownote作りました。

## 4: Support library
- arakiさん自己紹介
- Support libraryについて
  - 各libraryのoverview的な
  - 重要な告知的なことは support-v4 の小分けの話と最小 SDK バージョン上げる話ですかね。
  - CoordinatorLayout
  - FlexboxLayout
  - ConstraintLayout
- 告知 `黒帯エンジニアが教える プロの技術 Android開発の教科書`
  - 6/18 に「黒帯エンジニアが教える プロの技術 Android開発の教科書」が発売されました。

```
総合的に、Android Studioの使い方から、設計、実装、テスト、CIを利用してビルドやアプリの配布、ストアへのリリース、KPIを確認しつつ改善を行うなど、Androidアプリの開発・運営に必要なことが一冊に詰まっています。
エンジニアがレベルアップするにはベストな一冊。デザイン・グロースについても記載しているのでPMの読み物としても最適です。
```
- How you'd become a Googler and started working on support library? Tell us your story.
- How do you usually work with other members? For example, I'm afraid working with Chris might be hard due to the time difference.
- It seems to me Android is developed by many small teams, each of which is of only a few members. - How come? Do you think it's efficient?
- Sometimes I feel like a library published by a Googler is not inconsistent with the Android platform, like Agera. How do you think we, Android app. developers, should see that?
- What is your expectation to the Android app. developers?
- How do you think about Android tech communities? And especially about Japanese ones?
- Support libraryの意思決定はどの様にしているのか？(どのコンポーネントを実装するか、優先順位等)
- デザイナーとの協業はどの様にしている？
- 下位互換性は実際どの様に担保しているのか

**Comment by yaraki** [comment]
thagikura が出るということなので FlexboxLayout にはちょっと触れるだけで詳細は温存しましょう

**Comment by hotchemi** [comment]
@yaraki Shownoteに貼りたいリンクがあればこちらに宜しくお願い致します！

**Comment by hotchemi** [comment]
design support library
NavigationView
BottomSheet
CoordinatorLayout

総合的に、Android Studioの使い方から、設計、実装、テスト、CIを利用してビルドやアプリの配布、ストアへのリリース、KPIを確認しつつ改善を行うなど、Androidアプリの開発・運営に必要なことが一冊に詰まっています。
エンジニアがレベルアップするにはベストな一冊。デザイン・グロースについても記載しているのでPMの読み物としても最適です。
